config/routes.rb
Rails.application.routes.draw do
  resources :playlist_musicas
  resources :playlists
  resources :musicas
  resources :usuarios
  root to: 'visitors#index'

end

app/models/musica.rb
class Musica < ActiveRecord::Base
  belongs_to :usuario
  has_many :playlist_musicas
  belongs_to :playlist
end

app/controllers/musicas_controller.rb
class MusicasController < ApplicationController
  before_action :set_musica, only: [:show, :edit, :update, :destroy]

  # GET /musicas
  # GET /musicas.json
  def index
    @musicas = Musica.all
  end

  # GET /musicas/1
  # GET /musicas/1.json
  def show
  end

  # GET /musicas/new
  def new
    @musica = Musica.new
  end

  # GET /musicas/1/edit
  def edit
  end

  # POST /musicas
  # POST /musicas.json
  def create
    @musica = Musica.new(musica_params)

    respond_to do |format|
      if @musica.save
        format.html { redirect_to @musica, notice: 'Musica was successfully created.' }
        format.json { render :show, status: :created, location: @musica }
      else
        format.html { render :new }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musicas/1
  # PATCH/PUT /musicas/1.json
  def update
    respond_to do |format|
      if @musica.update(musica_params)
        format.html { redirect_to @musica, notice: 'Musica was successfully updated.' }
        format.json { render :show, status: :ok, location: @musica }
      else
        format.html { render :edit }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicas/1
  # DELETE /musicas/1.json
  def destroy
    @musica.destroy
    respond_to do |format|
      format.html { redirect_to musicas_url, notice: 'Musica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musica
      @musica = Musica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musica_params
      params.require(:musica).permit(:idmusic, :nome, :tamanho, :genero, :artista, :album, :usuario_id)
    end
end

app/helpers/musicas_helper.rb
module MusicasHelper
end

app/views/musicas/_form.html.haml
= simple_form_for(@musica) do |f|
  = f.error_notification

  
  .form-inputs
    = f.input :idmusic
    = f.input :nome
    = f.input :tamanho
    = f.input :genero
    = f.input :artista
    = f.input :album
    = f.association :usuario, label_method: :username

  .form-actions
    = f.submit "Salvar"

app/views/musicas/edit.html.haml
%h1 Editando a musica

= render 'form'

= link_to 'Detalhes', @musica, :class => 'allbt'
\|
= link_to 'Voltar', musicas_path, :class => 'allbt'

app/views/musicas/index.html.haml
%h1 Todas as musicas

%table
  %thead
    %tr
      %div.tabletitle
        %th Idmusic
        %th Nome
        %th Tamanho
        %th Genero
        %th Artista
        %th Album
        %th Usuario

  %tbody
    - @musicas.each do |musica|
      %tr
        %td= musica.idmusic
        %td= musica.nome
        %td= musica.tamanho
        %td= musica.genero
        %td= musica.artista
        %td= musica.album
        %td= musica.usuario.username if !musica.usuario.nil?
        %td= link_to 'Detalhes', musica, :class => 'allbt'
        %td= link_to 'Editar', edit_musica_path(musica), :class => 'allbt'
        %td= link_to 'Excluir', musica, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'allbt'

%br

= link_to 'Adicionar nova Musica', new_musica_path, :class => 'allbt'

app/views/musicas/new.html.haml
%h1 Adicionando nova musica

= render 'form'

= link_to 'Voltar', musicas_path, :class => 'allbt'

app/views/musicas/show.html.haml
%h1 Detalhes da musica

%div.dt
  %p
    %b Idmusic:
    = @musica.idmusic
  %p
    %b Nome:
    = @musica.nome
  %p
    %b Tamanho:
    = @musica.tamanho
  %p
    %b Genero:
    = @musica.genero
  %p
    %b Artista:
    = @musica.artista
  %p
    %b Album:
    = @musica.album
  %p
    %b Usuario:
    = @musica.usuario.username

= link_to 'Editar', edit_musica_path(@musica), :class => 'allbt'
\|
= link_to 'Voltar', musicas_path, :class => 'allbt'