config/routes.rb
Rails.application.routes.draw do
  resources :playlist_musicas
  resources :playlists
  resources :musicas
  resources :usuarios
  root to: 'visitors#index'

end

app/models/playlist_musica.rb
class PlaylistMusica < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :musica                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
end

app/controllers/playlist_musicas_controller.rb
class PlaylistMusicasController < ApplicationController
  before_action :set_playlist_musica, only: [:show, :edit, :update, :destroy]

  # GET /playlist_musicas
  # GET /playlist_musicas.json
  def index
    @playlist_musicas = PlaylistMusica.all
  end

  # GET /playlist_musicas/1
  # GET /playlist_musicas/1.json
  def show
  end

  # GET /playlist_musicas/new
  def new
    @playlist_musica = PlaylistMusica.new
  end

  # GET /playlist_musicas/1/edit
  def edit
  end

  # POST /playlist_musicas
  # POST /playlist_musicas.json
  def create
    @playlist_musica = PlaylistMusica.new(playlist_musica_params)

    respond_to do |format|
      if @playlist_musica.save
        format.html { redirect_to @playlist_musica, notice: 'Playlist musica was successfully created.' }
        format.json { render :show, status: :created, location: @playlist_musica }
      else
        format.html { render :new }
        format.json { render json: @playlist_musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlist_musicas/1
  # PATCH/PUT /playlist_musicas/1.json
  def update
    respond_to do |format|
      if @playlist_musica.update(playlist_musica_params)
        format.html { redirect_to @playlist_musica, notice: 'Playlist musica was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist_musica }
      else
        format.html { render :edit }
        format.json { render json: @playlist_musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlist_musicas/1
  # DELETE /playlist_musicas/1.json
  def destroy
    @playlist_musica.destroy
    respond_to do |format|
      format.html { redirect_to playlist_musicas_url, notice: 'Playlist musica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist_musica
      @playlist_musica = PlaylistMusica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_musica_params
      params.require(:playlist_musica).permit(:playlist_id, :musica_id)
    end
end

app/helpers/playlist_musicas_helper.rb
module PlaylistMusicasHelper
end

app/views/playlist_musicas/_form.html.haml
= simple_form_for(@playlist_musica) do |f|
  = f.error_notification

  .form-inputs
    = f.association :playlist, label_method: :nome
    = f.association :musica, label_method: :nome

  .form-actions
    = f.submit "Salvar"

app/views/playlist_musicas/edit.html.haml
%h1 Editar musica da playlist

= render 'form'

= link_to 'Detalhes', @playlist_musica, :class => 'allbt'
\|
= link_to 'Voltar', playlist_musicas_path, :class => 'allbt'

app/views/playlist_musicas/index.html.haml
%h1 Gerenciar lista de musicas

%table.allbt2.aw
  %thead
    %tr
      %th Playlist
      %th Musica
      %th
      %th
      %th

  %tbody
    - @playlist_musicas.each do |playlist_musica|
      %tr
        %td= playlist_musica.playlist.nome
        %td= playlist_musica.musica.nome
        %td= link_to 'Detalhes', playlist_musica, :class => 'allbt'
        %td= link_to 'Editar', edit_playlist_musica_path(playlist_musica), :class => 'allbt'
        %td= link_to 'Excluir', playlist_musica, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'allbt'

%br

= link_to 'Adicionar musicas', new_playlist_musica_path, :class => 'allbt'

app/views/playlist_musicas/new.html.haml
%h1 New playlist_musica

= render 'form'

= link_to 'Voltar', playlist_musicas_path, :class => 'allbt'

app/views/playlist_musicas/show.html.haml
%p#notice= notice

%div.dt
	%p
		%b Playlist:
		= @playlist_musica.playlist.nome
	%p
		%b Musica:
		= @playlist_musica.musica.nome

= link_to 'Editar', edit_playlist_musica_path(@playlist_musica), :class => 'allbt'
\|
= link_to 'Voltar', playlist_musicas_path, :class => 'allbt'