config/routes.rb
Rails.application.routes.draw do
  resources :playlist_musicas
  resources :playlists
  resources :musicas
  resources :usuarios
  root to: 'visitors#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	has_many :playlist_musicas
	has_many :musicas
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:nome)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.haml
= simple_form_for(@playlist) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome

  .form-actions
    = f.submit "Salvar"

app/views/playlists/edit.html.haml
%h1 Editar nome da playlist

= render 'form'

= link_to 'Detalhes', @playlist
\|
= link_to 'Voltar', playlists_path

app/views/playlists/index.html.haml
%h1  Todas as Playlists

%table.allbt2
  %thead
    %tr
      %th Nome
      %th
      %th
      %th

  %tbody
    - @playlists.each do |playlist|
      %tr
        %td= playlist.nome
        %td= link_to 'Detalhes', playlist, :class => 'allbt'
        %td= link_to 'Editar', edit_playlist_path(playlist), :class => 'allbt'
        %td= link_to 'Excluir', playlist, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'allbt'


= link_to 'Nova playlist', new_playlist_path, :class => 'allbt'

app/views/playlists/new.html.haml
%h1 Nova playlist

= render 'form'

= link_to 'Voltar', playlists_path

app/views/playlists/show.html.haml
%h2 Detalhes da playlist

%div.dt
  %p
    %b Nome:
    = @playlist.nome

%h2 Musicas dessa playlist

%tbody
  - @playlist.playlist_musicas.each do |musica| 
    %tr
      %td= musica.musica.nome
    %br



= link_to 'Editar', edit_playlist_path(@playlist), :class => 'allbt'
\|
= link_to 'Voltar', playlists_path, :class => 'allbt'