config/routes.rb
Rails.application.routes.draw do
  resources :playlist_musicas
  resources :playlists
  resources :musicas
  resources :usuarios
  root to: 'visitors#index'

end

app/views/layouts/_footer.html.erb
<h5>In development | CompartMusic </h5>

<h5 id="ftsubtitle">development tools</h5>

<img class="devimg" src="https://achievement-images.teamtreehouse.com/badges_bonus_html5mobile.png"/>

<img class="devimg" src="https://achievement-images.teamtreehouse.com/CSS3.png">

<img class="devimg" src="https://achievement-images.teamtreehouse.com/badges_SimpleFacebook_Stage1.png">

<p class="fttitle">Hosted by:</p>
<img class="logo2" src="https://camo.githubusercontent.com/0428845048b06e15445db28452ca820b8207d95d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6b696e6c616e652d70726f64756374696f6e732f6170692d6576616e67656c6973742f6865726f6b752f6865726f6b752d6c6f676f2e706e67"/>

app/views/layouts/_header.html.erb
<!--<img src="http://www.ringophone.com/HDanimWP/NeonGirl1.gif">-->
<img class="logo" src="https://ap.imagensbrasil.org/images/logomain.png"/>
<h2 class="subtitle dois">Espaço</h2>
<h2 class="subtitle">Online</h2>
<nav>
<ul class="menu">
	<li><%= link_to 'Home', root_path %></li>
	<li><%= link_to 'Musicas', musicas_path %></li>
	<li><%= link_to 'Usuarios', usuarios_path %></li>
	<li><%= link_to 'Playlists', playlists_path %></li>
	<li><%= link_to 'Gerenciar playlist', playlist_musicas_path %></li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compartmusic ONLINE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="all">
	<header class="hd">
		<%= render 'layouts/header' %>
	</header>
	<div class="main">
		<%= yield %>
	</div>
</div>
<footer class="ft">
	<%= render 'layouts/footer' %>
</footer>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ :charset => "utf-8" }
  %body
    %header
      = render 'layouts/header'
    %main{:role => "main"}
      = yield
    %footer
      = render 'layouts/footer'
     